(() => {
  'use strict';
  const data=window.portfolioData||{}, $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const mark=v=>esc(v).replace(/\*\*(.+?)\*\*/g,'<mark>$1</mark>');
  const headline=v=>esc(v).replace(/\*\*(.+?)\*\*/,'<span class="gradient-text">$1</span>');
  const names={scikitlearn:'Scikit-learn',dotnet:'.NET',cplusplus:'C/C++',cnn:'CNN',bilstm:'BiLSTM',videomae:'VideoMAE',tensorflowjs:'TensorFlow.js',fastapi:'FastAPI',opencv:'OpenCV',stm32:'STM32',fiberoptics:'Fiber optics',ssfm:'SSFM',photonics:'Photonics',tsl:'Tunisian Sign Language',tts:'Text-to-speech',smtp:'SMTP',reportlab:'ReportLab',dsp:'DSP',uart:'UART',freertos:'FreeRTOS',opticalcommunications:'Optical communications',huggingface:'Hugging Face',llama:'LLaMA'};
  const label=k=>names[k]||k.replace(/(^|[-_])\w/g,x=>x.toUpperCase()).replace(/[-_]/g,' ');
  const images={python:'python',numpy:'numpy',pandas:'pandas',jupyter:'jupyter',matlab:'matlab',tensorflow:'tensorflow',pytorch:'pytorch',scikitlearn:'scikitlearn',keras:'keras',html5:'html5',css3:'css3',dotnet:'dotnetcore',mysql:'mysql',postgresql:'postgresql',sqlite:'sqlite',git:'git',github:'github',docker:'docker',linux:'linux',bash:'bash',react:'react',fastapi:'fastapi',redis:'redis',wordpress:'wordpress',arduino:'arduino',opencv:'opencv',cplusplus:'cplusplus'};
  const masks={mediapipe:'si-mediapipe',huggingface:'si-huggingface',ollama:'si-ollama',llama:'si-meta',deepseek:'si-deepseek',gemini:'si-googlegemini',streamlit:'si-streamlit',latex:'si-latex'};
  const glyph=k=>images[k]?`<img src="assets/icons/${images[k]}.svg" alt="" width="32" height="32" loading="lazy" decoding="async">`:masks[k]?`<span class="ico-mask" style="--src:url('assets/icons/${masks[k]}.svg')" aria-hidden="true"></span>`:`<span class="ico-mono" aria-hidden="true">${esc(({groq:'Gq',gemma:'Ge'})[k]||label(k).split(/[\s+.-]/).map(x=>x[0]||'').join('').slice(0,2).toUpperCase())}</span>`;
  const stack=keys=>`<div class="stack-row" aria-label="Technology stack">${(keys||[]).map(k=>`<span class="stack-icon" title="${esc(label(k))}">${glyph(k)}<span>${esc(label(k))}</span></span>`).join('')}</div>`;
  const imageButton=(src,alt,gallery,index,cls='',stagger=false)=>`<button type="button" class="gallery-thumb ${cls}" ${stagger?'data-stagger':''} data-gallery="${esc(gallery)}" data-index="${index}" aria-label="Open ${esc(alt)} in image viewer"><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy" decoding="async"></button>`;
  const galleryMap={}, projectList=$('#project-list'), projects=data.projects||[];
  const renderProjects=()=>{
    if(!projectList)return;
    projectList.innerHTML=projects.map((p,index)=>{const id=`project-${p.id}`,imgs=p.images||[];galleryMap[id]=imgs.map((src,i)=>({src,caption:`${p.title} - photo ${i+1}`}));
      return `<article class="project-card" id="${esc(id)}" data-stagger><div class="project-card-head"><span>PROJECT / ${String(index+1).padStart(2,'0')}</span><button class="project-expand" type="button" aria-label="Expand ${esc(p.title)} details" aria-expanded="false" aria-controls="${id}-details"><span aria-hidden="true">&#8599;</span></button></div><p class="project-context">${esc(p.context)}</p><p class="project-type">${esc((p.stack||[]).slice(0,3).map(label).join(' · '))}</p><h3>${esc(p.title)}</h3><div class="project-gallery" data-count="${imgs.length}">${imgs.slice(0,3).map((src,i)=>imageButton(src,`${p.title} project photo ${i+1}`,id,i)).join('')}${imgs.length>3?`<button class="project-more-photos" type="button" data-gallery="${id}" data-index="3">+${imgs.length-3}</button>`:''}</div><div class="project-copy"><p class="project-headline">${headline(p.headline)}</p><ul class="project-impact" aria-label="Project highlights">${(p.impact||[]).slice(0,3).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${stack(p.stack)}<div class="project-detail" id="${id}-details" hidden><div><b>Challenge</b><p>${mark(p.problem||'')}</p></div><div><b>Solution</b><p>${mark((p.approach||p.bullets||[]).join(' '))}</p></div><div><b>Result</b><p>${mark(p.result||p.outcome||'')}</p></div><button class="case-open" type="button" data-case-id="${esc(p.id)}">Full project details <span aria-hidden="true">&#8599;</span></button></div></div></article>`;
    }).join('');
    const repos=$('#repo-list');if(repos)repos.innerHTML=projects.filter(p=>p.links?.github).map(p=>`<li data-stagger><div>${stack(p.stack)}<h3>${esc(p.title)}</h3><p>${esc((p.bullets||[])[0]||p.headline.replace(/\*\*/g,''))}</p></div><a href="${esc(p.links.github)}" target="_blank" rel="noopener noreferrer">View source <span aria-hidden="true">&#8599;</span></a></li>`).join('');
  };
  const renderSkills=()=>{const root=$('#skills-grid'),groups=data.skills||[];if(!root)return;root.innerHTML=`<div class="skill-board"><div class="skill-nodes" role="tablist" aria-label="Skill areas">${groups.map((g,i)=>`<button type="button" class="skill-node${i===0?' active':''}" role="tab" id="skill-tab-${i}" aria-selected="${i===0}" aria-controls="skill-panel" style="--x:${[12,47,83,75,18,39,79][i%7]}%;--y:${[20,10,30,72,78,88,52][i%7]}%">${esc(g.category)}</button>`).join('')}</div><section class="skill-story" id="skill-panel" role="tabpanel" aria-labelledby="skill-tab-0"></section></div>`;const panel=$('#skill-panel',root);const show=i=>{const g=groups[i];if(!g)return;$$('.skill-node',root).forEach((n,k)=>{n.classList.toggle('active',i===k);n.setAttribute('aria-selected',String(i===k));});panel.setAttribute('aria-labelledby',`skill-tab-${i}`);panel.innerHTML=`<span class="skill-node-label">NODE / ${String(i+1).padStart(2,'0')}</span><h3>${esc(g.category)}</h3><p>${esc(g.description||'Tools and methods I use in technical work.')}</p><ul class="skill-items">${g.items.map(k=>`<li class="skill-item" title="${esc(label(k))}">${glyph(k)}<span>${esc(label(k))}</span></li>`).join('')}</ul><small>USED IN · ${esc(g.whereUsed||'Technical and research projects')}</small>`;};$$('.skill-node',root).forEach((n,i)=>{n.addEventListener('click',()=>show(i));n.addEventListener('focus',()=>show(i));});show(0);};
  const renderResearch=()=>{const root=$('#research-list');if(!root)return;const order=['talan-research','sfm-internship','fiber-laser-research','tunilip-research'],items=[...(data.researchExperiences||[])].sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
    root.innerHTML=items.map(e=>`<article class="tl-item" id="experience-${esc(e.id)}" data-stagger><div class="tl-date"><b>${esc(e.period.replace('June-August','Jun – Aug').replace('July-August','Jul – Aug').replace('October 2025-April 2026','Oct 2025 – Apr 2026').replace('October 2024-April 2025','Oct 2024 – Apr 2025'))}</b><span>${esc(e.organization)}</span></div><div class="tl-card"><p class="experience-context">${esc(e.context)}</p><h3>${esc(e.role)}</h3><p class="lead">${esc(e.outcome)}</p><ul>${(e.bullets||[]).slice(0,4).map(b=>`<li>${mark(b)}</li>`).join('')}</ul>${stack(e.stack)}${e.projectId?`<a class="experience-link" href="#project-${esc(e.projectId)}">View project <span aria-hidden="true">&#8599;</span></a>`:''}</div></article>`).join('');};
  const caption=src=>decodeURIComponent(src.split('/').pop().replace(/\.[^.]+$/,'')).replace(/[ _-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).replace(/Tehnical/gi,'Technical').replace(/Contineous/gi,'Continuous');
  const renderRing=(imgs,id,title)=>{const n=imgs.length;if(n<2)return'';const step=360/n;return `<div class="ring" data-ring><div class="ring-track">${imgs.map((src,i)=>`<figure class="ring-card" style="--angle:${i*step}deg"><button type="button" data-gallery="${esc(id)}" data-index="${i}" aria-label="Open ${esc(caption(src))} photo"><img src="${esc(src)}" alt="${esc(caption(src))}" loading="lazy" decoding="async"><figcaption>${esc(caption(src))}</figcaption></button></figure>`).join('')}</div><div class="ring-controls"><button type="button" data-ring-step="-1" aria-label="Previous photo">&#8249;</button><span class="ring-count" aria-live="polite">CARD 01 / ${String(n).padStart(2,'0')}</span><button type="button" data-ring-step="1" aria-label="Next photo">&#8250;</button></div><p class="ring-hint">HOVER TO PAUSE · CLICK A CARD TO OPEN</p></div>`;};
  const mountRing=root=>{const track=$('.ring-track',root),cards=$$('.ring-card',root),count=$('.ring-count',root);if(!track)return;const n=cards.length,cw=matchMedia('(max-width: 800px)').matches?150:220,r=Math.round((cw/2)/Math.tan(Math.PI/Math.max(n,3)))+28;root.style.setProperty('--ring-card-width',`${cw}px`);root.style.setProperty('--ring-radius',`${r}px`);let spin=0,paused=false,visible=false,raf=0;const paint=()=>{if(!root.isConnected){cancelAnimationFrame(raf);return;}if(visible&&!paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches)spin=(spin+.08)%360;track.style.transform=`translate(-50%,-50%) rotateY(${-spin}deg)`;const front=((Math.round(spin/(360/n))%n)+n)%n;count.textContent=`CARD ${String(front+1).padStart(2,'0')} / ${String(n).padStart(2,'0')}`;raf=requestAnimationFrame(paint);};root.addEventListener('pointerenter',()=>paused=true);root.addEventListener('pointerleave',()=>paused=false);let downX=null;root.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;downX=e.clientX;paused=true;root.setPointerCapture?.(e.pointerId);});root.addEventListener('pointermove',e=>{if(downX===null)return;spin-=(e.clientX-downX)*.35;downX=e.clientX;});root.addEventListener('pointerup',()=>{downX=null;paused=false;});$$('[data-ring-step]',root).forEach(b=>b.addEventListener('click',()=>{spin+=Number(b.dataset.ringStep)*(360/n);paused=true;setTimeout(()=>paused=false,650);}));const io=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible&&!raf)raf=requestAnimationFrame(paint);if(!visible){cancelAnimationFrame(raf);raf=0;}});io.observe(root);};
  let activeRole=0;
  const renderCommunity=()=>{const tabs=$('#role-selector'),detail=$('#community-detail'),roles=data.volunteering||[];if(!tabs||!detail)return;
    tabs.innerHTML=roles.map((v,i)=>`<button class="role-tab" id="role-tab-${esc(v.id)}" type="button" role="tab" aria-selected="${i===activeRole}" aria-controls="community-detail" tabindex="${i===activeRole?0:-1}" data-role-index="${i}"><span class="role-mark">${esc(v.mark||'IEEE')}</span><span><span class="role-tab-title">${esc(v.title)}</span><span class="role-tab-org">${esc(v.organization)} · ${esc(v.period)}</span></span></button>`).join('');const v=roles[activeRole];if(!v)return;
    const id=`volunteer-${v.id}`,imgs=v.gallery||[];galleryMap[id]=imgs.map(src=>({src,caption:caption(src)}));const gal=imgs.length===1?`<button class="community-still" type="button" data-gallery="${id}" data-index="0" aria-label="View ${esc(v.title)} photo"><img src="${esc(imgs[0])}" alt="${esc(caption(imgs[0]))}" loading="lazy"></button>`:renderRing(imgs,id,v.title);
    detail.setAttribute('aria-labelledby',`role-tab-${v.id}`);detail.innerHTML=`${v.awardImage?'<span class="award-label">Rising Star Member Award 2025</span>':''}<p class="period">${esc(v.period)}</p><h3>${esc(v.title)}</h3><p class="community-org">${esc(v.organization)}</p><p>${esc(v.description)}</p>${v.link?`<a class="community-link" href="${esc(v.link.url)}" target="_blank" rel="noreferrer">${esc(v.link.label)} &#8599;</a>`:''}${gal}${imgs.length>1?`<button class="view-all-photos" type="button" data-gallery="${id}" data-index="0">View all ${imgs.length} photos</button>`:''}`;mountRing($('.ring',detail));
  };
  const wireCarousel=root=>{const track=$('.carousel-track',root);if(!track)return;const slides=$$('.carousel-slide',track),dots=$$('.carousel-dot',root);const go=i=>{i=(i+slides.length)%slides.length;track.scrollTo({left:slides[i].offsetLeft-track.offsetLeft,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};$$('[data-dir]',root).forEach(b=>b.addEventListener('click',()=>{const current=Math.round(track.scrollLeft/(slides[0]?.offsetWidth+10||1));go(current+Number(b.dataset.dir));}));dots.forEach(d=>d.addEventListener('click',()=>go(Number(d.dataset.dot))));let frame=0;track.addEventListener('scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const i=Math.max(0,Math.min(dots.length-1,Math.round(track.scrollLeft/(slides[0]?.offsetWidth+10||1))));dots.forEach((d,n)=>d.setAttribute('aria-current',String(i===n)));});},{passive:true});track.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();go(Math.round(track.scrollLeft/(slides[0]?.offsetWidth+10||1))+(e.key==='ArrowRight'?1:-1));}});};
  const renderDesigns=()=>{const root=$('#design-grid'),items=data.designs||[],id='designs',button=$('#show-designs');if(!root)return;galleryMap[id]=items.map(src=>({src,caption:caption(src)}));let expanded=false;const draw=()=>{root.innerHTML=items.slice(0,expanded?items.length:12).map((src,i)=>imageButton(src,`Design project ${i+1}`,id,i,'design-thumb',true)).join('');if(button){button.hidden=items.length<=12;button.textContent=expanded?'Show fewer':'Show more designs';button.setAttribute('aria-expanded',String(expanded));}};button?.addEventListener('click',()=>{expanded=!expanded;draw();if(window.gsap)window.gsap.to($$('.design-thumb',root),{y:0,opacity:1,stagger:.035,duration:.3,ease:'power2.out',overwrite:true});else $$('.design-thumb',root).forEach(tile=>{tile.style.opacity='1';tile.style.transform='none';});});draw();};
  renderProjects();renderSkills();renderResearch();renderCommunity();renderDesigns();
  $('#projects')?.after($('#skills'));
  document.addEventListener('click',e=>{const button=e.target.closest('.project-expand');if(!button)return;const card=button.closest('.project-card'),panel=$('.project-detail',card),open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));panel.hidden=!open;card.classList.toggle('is-expanded',open);});
  if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
    $$('.project-card').forEach(card=>{
      card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),rx=(r.height/2-(e.clientY-r.top))/18,ry=((e.clientX-r.left)-r.width/2)/18;card.style.transform=`perspective(1200px) rotateX(${rx}deg) rotateY(${ry}deg) translateY(-2px)`;});
      card.addEventListener('pointerleave',()=>{card.style.transform='';});
    });
  }
  const caseDlg=$('#case-dialog'),lightbox=$('#lightbox'),lbImg=$('.lightbox-image',lightbox),lbCaption=$('.lightbox-caption span',lightbox),lbCount=$('.lightbox-count',lightbox),lbPrev=$('.lightbox-prev',lightbox),lbNext=$('.lightbox-next',lightbox);let lbPool=[],lbIndex=0,lastFocus=null;
  const updateLightbox=()=>{const item=lbPool[lbIndex];lbImg.src=item.src;lbImg.alt=item.caption;lbCaption.textContent=item.caption;lbCount.textContent=`${lbIndex+1} / ${lbPool.length}`;lbPrev.disabled=lbNext.disabled=lbPool.length<2;};
  const openGallery=(id,index=0,trigger)=>{lbPool=galleryMap[id]||[];if(!lbPool.length)return;lbIndex=Math.max(0,Math.min(lbPool.length-1,index));lastFocus=trigger||document.activeElement;updateLightbox();lightbox.showModal();window.lenis?.stop();$('.lightbox-close',lightbox).focus();};
  const closeScroll=()=>{if(!caseDlg.open&&!lightbox.open)window.lenis?.start();};
  const openCase=p=>{if(!p||!caseDlg)return;lastFocus=document.activeElement;const body=$('.case-body',caseDlg),links=Object.entries(p.links||{}).filter(([,u])=>u).map(([k,u])=>`<a class="button button-outline" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${k==='github'?'View source':k==='report'?'Read report':'Open project'} &#8599;</a>`).join('');
    body.innerHTML=`<span class="pill case-anim">${esc(p.context)}</span><h2 id="case-title" class="case-anim">${esc(p.title)}</h2><p class="lead case-anim">${headline(p.headline)}</p><ul class="project-impact case-anim">${(p.impact||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="case-grid"><section class="case-block case-anim"><h4>Problem</h4><p>${mark(p.problem||'')}</p></section><section class="case-block case-anim"><h4>Approach</h4><ul>${(p.approach||p.bullets||[]).map(x=>`<li>${mark(x)}</li>`).join('')}</ul></section><section class="case-block case-anim"><h4>Result</h4><p>${mark(p.result||p.outcome||'')}</p></section></div><h3 class="case-gallery-title case-anim">Project gallery</h3><div class="case-gallery case-anim">${(p.images||[]).map((src,i)=>imageButton(src,`${p.title} project photo ${i+1}`,`project-${p.id}`,i)).join('')}</div>${stack(p.stack)}<div class="case-links">${links}</div>`;
    caseDlg.showModal();window.lenis?.stop();$('.case-close',caseDlg).focus();if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches){window.gsap.fromTo('.case-panel',{x:70,opacity:.7},{x:0,opacity:1,duration:.48,ease:'power3.out'});window.gsap.from('.case-anim',{y:18,opacity:0,stagger:.045,delay:.1,duration:.48,ease:'power2.out'});}
  };
  document.addEventListener('click',e=>{const gal=e.target.closest('[data-gallery]');if(gal){openGallery(gal.dataset.gallery,Number(gal.dataset.index),gal);return;}const open=e.target.closest('[data-case-id]');if(open)openCase(projects.find(p=>p.id===open.dataset.caseId));});
  const step=d=>{if(lbPool.length<2)return;lbIndex=(lbIndex+d+lbPool.length)%lbPool.length;updateLightbox();};lbPrev.addEventListener('click',()=>step(-1));lbNext.addEventListener('click',()=>step(1));$('.lightbox-close',lightbox).addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close();});lightbox.addEventListener('close',()=>{lastFocus?.focus?.();closeScroll();});$('.case-close',caseDlg).addEventListener('click',()=>caseDlg.close());caseDlg.addEventListener('click',e=>{if(e.target===caseDlg)caseDlg.close();});caseDlg.addEventListener('close',()=>{lastFocus?.focus?.();closeScroll();});document.addEventListener('keydown',e=>{if(lightbox.open&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();step(e.key==='ArrowRight'?1:-1);}});
  let touch=0;lightbox.addEventListener('touchstart',e=>touch=e.changedTouches[0].clientX,{passive:true});lightbox.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touch;if(Math.abs(dx)>45)step(dx<0?1:-1);},{passive:true});
  const theme=$('#theme-toggle'),root=document.documentElement;try{const saved=localStorage.getItem('portfolio-theme');if(saved==='light'||saved==='dark')root.dataset.theme=saved;}catch{}const syncTheme=()=>{const dark=root.dataset.theme!=='light';theme.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');theme.innerHTML=`<span aria-hidden="true">${dark?'&#9788;':'&#9789;'}</span>`;const m=$('meta[name="theme-color"]');m?.setAttribute('content',dark?'#0d0f12':'#f6f4fb');};syncTheme();theme.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('portfolio-theme',root.dataset.theme);}catch{}syncTheme();});
  const roles=$('#role-selector');roles?.addEventListener('click',e=>{const tab=e.target.closest('[data-role-index]');if(!tab)return;activeRole=Number(tab.dataset.roleIndex);renderCommunity();$('#role-tab-'+data.volunteering[activeRole].id)?.focus();});roles?.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();const n=(data.volunteering||[]).length;activeRole=e.key==='Home'?0:e.key==='End'?n-1:(activeRole+(e.key==='ArrowDown'?1:-1)+n)%n;renderCommunity();$('#role-tab-'+data.volunteering[activeRole].id)?.focus();});
  const toggle=$('#nav-toggle'),nav=$('#nav-links');toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');nav.classList.toggle('is-open',open);document.body.classList.toggle('menu-open',open);if(open&&window.gsap)window.gsap.from($$('.nav-links li',nav),{y:18,opacity:0,stagger:.045,duration:.35,ease:'power2.out'});});nav?.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('is-open')){nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');document.body.classList.remove('menu-open');toggle.focus();}});
  const header=$('#site-header'),navLinks=$$('.nav-links a[href^="#"]'),indicator=$('#nav-indicator');let lastY=scrollY;const moveIndicator=a=>{if(!a||!indicator)return;const n=$('.nav').getBoundingClientRect(),r=a.getBoundingClientRect();indicator.style.left=`${r.left-n.left}px`;indicator.style.width=`${r.width}px`;indicator.style.opacity='1';};const sectionObserver=new IntersectionObserver(entries=>entries.forEach(en=>{if(!en.isIntersecting)return;const a=navLinks.find(x=>x.hash===`#${en.target.id}`);navLinks.forEach(x=>x.removeAttribute('aria-current'));if(a){a.setAttribute('aria-current','location');moveIndicator(a);}}),{rootMargin:'-35% 0px -55% 0px'});navLinks.forEach(a=>{const s=$(a.hash);if(s)sectionObserver.observe(s);});window.addEventListener('resize',()=>moveIndicator(navLinks.find(a=>a.hasAttribute('aria-current'))));window.addEventListener('scroll',()=>{const y=scrollY;header?.classList.toggle('is-hidden',y>lastY&&y>150&&!nav?.classList.contains('is-open'));lastY=y;const p=$('.scroll-progress');if(p)p.style.transform=`scaleX(${y/(document.documentElement.scrollHeight-innerHeight||1)})`;},{passive:true});
  const form=$('#contact-form');form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),subject=encodeURIComponent(`Portfolio message from ${fd.get('name')}`),body=encodeURIComponent(`${fd.get('message')}\n\nFrom: ${fd.get('name')} (${fd.get('email')})`);location.href=`mailto:yosser.jabloun@etudiant-enit.utm.tn?subject=${subject}&body=${body}`;});
  $('#copy-email')?.addEventListener('click',async e=>{const b=e.currentTarget;try{await navigator.clipboard.writeText('yosser.jabloun@etudiant-enit.utm.tn');b.textContent='Copied ✓';setTimeout(()=>b.textContent='Copy email',2000);}catch{location.href='mailto:yosser.jabloun@etudiant-enit.utm.tn';}});
  $('#back-top')?.addEventListener('click',e=>{e.preventDefault();window.lenis?window.lenis.scrollTo(0):scrollTo({top:0,behavior:'smooth'});});$('#year').textContent=new Date().getFullYear();
  $$('.section-head').forEach(x=>x.setAttribute('data-reveal',''));$$('.education-card,.website-card,.about-grid,.contact-copy-wrap,.contact-form,.community-layout').forEach(x=>x.setAttribute('data-stagger',''));$$('.reveal').forEach(x=>{x.classList.remove('reveal');x.classList.remove('is-visible');});
  const boot=$('#boot-screen'),finishBoot=()=>{if(document.body.classList.contains('is-ready'))return;clearTimeout(window.portfolioBootTimer);document.removeEventListener('keydown',skipBoot);boot?.removeEventListener('click',skipBoot);try{sessionStorage.setItem('portfolio-booted','1');}catch{}if(window.gsap&&boot&&!matchMedia('(prefers-reduced-motion: reduce)').matches)window.gsap.to(boot,{opacity:0,duration:.35,onComplete:()=>boot.remove()});else boot?.remove();document.body.classList.add('is-ready');if(window.initPortfolioMotion)window.initPortfolioMotion();};
  const skipBoot=()=>finishBoot();let seen=false;try{seen=sessionStorage.getItem('portfolio-booted')==='1';}catch{}if(!boot||seen||matchMedia('(prefers-reduced-motion: reduce)').matches)finishBoot();else{document.addEventListener('keydown',skipBoot,{once:true});boot.addEventListener('click',skipBoot,{once:true});if(window.gsap){window.gsap.set('.boot-inner li',{opacity:0,y:8});window.gsap.timeline({onComplete:finishBoot}).to('.boot-inner li',{opacity:1,y:0,stagger:.18,duration:.17,ease:'power2.out'}).to('.boot-bar i',{width:'100%',duration:.9,ease:'power2.inOut'},'-=.15');}else window.portfolioBootTimer=setTimeout(finishBoot,2100);}
})();
